name: public_hospital
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ^3.10.4
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  flutter_pdfview: ^1.4.4
  path_provider: ^2.1.5
  http: ^1.6.0
  syncfusion_flutter_pdfviewer: ^32.2.4
  printing: ^5.12.0
  intl: ^0.20.2
  pdf: ^3.11.3
  url_launcher: ^6.3.2
  image_picker: ^1.2.1
  jwt_decoder: ^2.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
analyzer:
  errors:
    file_names: ignore
flutter:
  assets:
    - assets/images/doctor.png
    - assets/images/blood.png
    - assets/images/ambulance.png
    - assets/images/logo.png
    - assets/images/person.png
    - assets/images/start.png
    - assets/images/end.png
    - assets/MedicalReport.pdf
    - assets/TestReport.pdf

  uses-material-design: true
